# Generated by Django 5.1.6 on 2025-03-12 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfLearn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='like_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
