# Generated by Django 5.1.6 on 2025-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dbbb',
            field=models.CharField(default=1, max_length=123),
        ),
    ]
