# Generated by Django 5.1.6 on 2025-03-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost'),
        ('blog', '0003_dog_dbbb'),
    ]

    operations = [
    ]
