# Generated by Django 5.1.6 on 2025-03-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_0003_blogpost_0003_dog_dbbb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dbbb',
        ),
    ]
